variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image:
    name: ${CI_REGISTRY}/ukos-git/docker-igorpro

test:
  script:
    - ln -rs vendor/plem/app "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/plem"
    - ln -rs vendor/filo/app "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/filo"
    - ln -rs vendor/utilities/app "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/utilities"
    - ln -rs vendor/utilities/vendor/plotly/src "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/plotly"
    - ln -rs vendor/json/json_functions.ipf "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/"
    - ln -rs vendor/json/win/x86/JSON.xop "/root/WaveMetrics/Igor Pro 8 User Files/Igor Extensions/"
    - ln -rs app "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/sma"
    - ln -rs vendor/plem/app "/root/WaveMetrics/Igor Pro 8 User Files/User Procedures/sma"
    - igorpro tests/tests.pxp  2>error.log | tee igorpro.log
    - if grep -e "^sma.*\.ipf.[0-9]\+.[0-9]\+.\serror." error.log; then exit 1; fi
  artifacts:
    paths:
      - error.log
